# Lets make Prediction on unseen data.

In [3]:
import joblib
import pandas as pd

model=joblib.load("/kaggle/input/models/nakulhemantkarpe/xgboost-for-sentinel-ops/scikitlearn/default/1/final_xgboost_model.pkl")

In [20]:
new_data=pd.DataFrame({
    "Air temperature [K]":[298.1,299.0,300.1,301.2,302.0,303.1,298.5,299.8,300.5,301.5,302.5,303.5,297.9,300.8,301.8,302.8,299.2,303.0,298.8,304.0],
    "Process temperature [K]":[308.6,309.2,310.1,311.5,312.0,313.2,308.7,309.8,310.5,311.6,312.5,313.8,308.4,310.8,311.8,312.8,309.5,313.0,309.0,314.0],
    "Rotational speed [rpm]":[1551,1408,1500,1800,1300,1200,1600,1450,1700,1350,1250,1100,1650,1500,1400,1300,1550,1150,1750,1000],
    "Torque [Nm]":[42.8,46.3,40.2,25.0,55.0,60.0,35.0,48.0,30.0,52.0,58.0,65.0,32.0,45.0,50.0,55.0,38.0,62.0,28.0,70.0],
    "Tool wear [min]":[0,3,108,180,200,240,30,50,150,180,210,250,10,120,160,220,70,230,140,260],
    "Type_L":[0,1,1,0,0,1,1,0,1,0,1,0,1,0,0,1,0,1,0,1],
    "Type_M":[1,0,0,1,0,0,1,1,0,1,0,1,0,1,1,0,1,0,1,0]
})

In [21]:
prediction=model.predict(new_data.to_numpy())
probability=model.predict_proba(new_data.to_numpy())[:,1]

In [22]:
results=pd.DataFrame({
    "prediction":prediction,
    "failure probability":probability
})

results

,prediction,failure probability
0,0,0.000606
1,0,0.001395
2,0,0.000570
3,0,0.002874
4,0,0.022098
5,1,0.866595
6,0,0.000804
7,0,0.002093
8,0,0.000838
9,0,0.002929


### multiple machine prediction
--
- The final XGBoost model was tested on 20 different machine conditions.
- The model predicted **14 machines as No Failure** and **6 machines as Failure**.
- Predicted failure probabilities varied considerably across the test inputs.
- The highest predicted failure probability was **95.14%**.
- The lowest predicted failure probability among predicted failures was **57.14%**.
- This demonstrates that the model responds differently to different machine operating conditions.